using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace js.pioneer.model
{
    public class AuditTrial
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public string Description { get; set; }
        public string SubscriptionNo { get; set; }
        public string UserNameWhoUpdated { get; set; }
        public DateTime Date { get; set; }
    }
}
