using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace js.pioneer.model
{
    public class LoyaltyUser
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public int LoyaltyUserId { get; set; }
        public string Name { get; set; }
    }
}
